# coding: utf-8

"""
    Document Service API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI
from sqlmodel import SQLModel

from openapi_server.apis.document_api import router as DocumentApiRouter
from openapi_server.database import engine

app = FastAPI(
    title="Document Service API",
    description="No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)",
    version="1.0.0",
)

SQLModel.metadata.create_all(engine)

app.include_router(DocumentApiRouter)
